### ISSUE TITLE
Custom name don't used hump type name

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss-easings#1]
In CSS, used the hyphen.

```css
.snake {
    transition: all 600ms ease-in-sine; √
}
.camel {
    transition: all 600ms easeInSine; ×
}
```
